apps/clientes/urls.py
from django.urls import path
from apps.clientes.views import index, plantilla, especial, especial2, ViewCliente, nuevoRegistro, editarRegistro, eliminarRegistro

app_name = 'clientes'

urlpatterns = [
	path('', index),
	path('index/', index),
	path('plantilla', plantilla, name = "plantilla"),
	path('especial', especial),
	path('especial2', especial2),
	path('especial3', ViewCliente.as_view(), name = "listaClientes"),
	path('nuevoRegistro', nuevoRegistro, name="nuevoRegistro"),
	path('editarRegistro/<idCliente>', editarRegistro, name="editarRegistro"),
	path('eliminarRegistro/<idCliente>', eliminarRegistro, name="eliminarRegistro"),
]

proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('apps.clientes.urls')),
]

apps/clientes/models.py
from django.db import models

# Create your models here.

class Cliente(models.Model):
	nombre = models.CharField(max_length = 30)
	apellidos = models.CharField(max_length = 30)

class Pedido(models.Model):
	cliente = models.ForeignKey(Cliente, null= True, blank = True, on_delete = models.CASCADE)
	

apps/clientes/forms.py
from django import forms
from apps.clientes.models import Cliente

class ClienteForm(forms.ModelForm):

	class Meta:
		model = Cliente

		fields = {
			'nombre',
			'apellidos',
		}

		labels = {
			'nombre': 'Nombre',
			'apellidos': 'Apellidos',
		}

		widgets = {
			'nombre' : forms.TextInput(attrs={'class': 'form-control'}),
			'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
		}

apps/clientes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView
from apps.clientes.models import Cliente
from apps.clientes.forms import ClienteForm
# Create your views here.
def index(request):
	#return HttpResponse("Esta es la respuesta")
	return render(request, 'clientes/index.html')

def plantilla(request):
	return render(request, 'clientes/index.html')

def especial(request):
	return render(request, 'clientes/paginaEspecial.html')

def especial2(request):
	contexto = {
	'clientes':Cliente.objects.all()
	}
	return render(request, 'clientes/paginaEspecial.html', contexto)

'''def especial2(request):
	return render(request, 'clientes/paginaEspecial.html', {clientes:Cliente.objects.all()})'''

class ViewCliente(ListView):
	model = Cliente
	#queryset si es necesario
	#queryset = Cliente.objects.filter(nombre='Juan')
	template_name = 'clientes/infoClientes.html'

#-----------------------------------

def nuevoRegistro(request):
	if request.method == 'POST':
		form = ClienteForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('clientes:listaClientes')
	else:
		form = ClienteForm()
	return render(request, 'clientes/nuevoFormulario.html', {'form': form})


def editarRegistro(request, idCliente):
	cliente = Cliente.objects.get(id = idCliente)
	if(request.method == 'GET'):
		form = ClienteForm(instance=cliente)
	else:
		form = ClienteForm(request.POST, instance=cliente)
		if form.is_valid():
			form.save();
		return redirect('clientes:listaClientes')
	return render(request, 'clientes/nuevoFormulario.html', {'form': form})


def eliminarRegistro(request, idCliente):
	cliente = Cliente.objects.get(id = idCliente)
	if(request.method == 'GET'):
		cliente.delete()
		return redirect('clientes:listaClientes')

templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Proyecto{% endblock %}</title>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">  {% block extracss %}{% endblock %}
</head>
<body>
	<header>{% block header %} {% include 'base/nav.html' %}{% endblock %}</header>
	<div>{% block content %}Contenido de la página{% endblock %}</div>
	<footer>{% block footer %}Taller Django 2018{% endblock footer %}</footer>

</body>
</html>

templates/base/info.html
<div class="container">
	<h1>Clientes</h1>
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th scope="col">No.</th>
				<th scope="col">Nombre</th>
				<th scope="col">Apellido</th>
			</tr>
		</thead>
		<tbody>
			{% for cliente in clientes %}
			<tr>
				<th scope="row">{{cliente.id}}</th>
				<td>{{cliente.nombre}}</td>
				<td>{{cliente.apellidos}}</td>
			</tr>
			{% empty %}
			<th>No hay clientes</th>
			{% endfor %}
		</tbody>
	</table>
</div>
<script type="text/javascript" src="js/bootstrap.js"></script>

templates/base/info2.html
<div class="container">
	<h1>Clientes</h1>
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th scope="col">No.</th>
				<th scope="col">Nombre</th>
				<th scope="col">Apellido</th>
				<th scope="col">Acciones</th>
			</tr>
		</thead>
		<tbody>
			{% for cliente in object_list %}
			<tr>
				<th scope="row">{{cliente.id}}</th>
				<td>{{cliente.nombre}}</td>
				<td>{{cliente.apellidos}}</td>
				<td>
					<a class="btn btn-primary mb-3" href="{% url 'clientes:editarRegistro' cliente.id %}">Editar</a>
					<a class="btn btn-primary mb-3" href="{% url 'clientes:eliminarRegistro' cliente.id  %}">Borrar</a>
				</td>
			</tr>
			{% empty %}
			<th>No hay clientes</th>
			{% endfor %}
		</tbody>
	</table>
</div>
<script type="text/javascript" src="js/bootstrap.js"></script>

templates/base/informacionAdicional.html
<ol>
	<li>Opción 1</li>
	<li>Opción 2</li>
	<li>Opción 3</li>
	<li>Opción 4</li>
	<li>Opción 5</li>
</ol

templates/base/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
	<a class="navbar-brand" href="tienda.html">Tienda</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" href="#">Clientes</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Pedidos</a>
			</li>
			<li class="nav-item active">
		    	<a class="nav-link" href="{% url 'clientes:listaClientes' %}">Home <span class="sr-only">(current)</span></a>
		  </li>
		</ul>
	</div>
</nav>

templates/clientes/index.html
{% extends 'base/index.html' %}
{% block title %}Nuevo título {% endblock %}
{% block content %}hol k ase {% endblock %}

templates/clientes/infoClientes.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/estilo_especial.css' %}">
{% endblock %}

{% block content %}

{% include 'base/info2.html' %}
<!--
{% for cliente in object_list %}
	<p>{{cliente.nombre}} {{cliente.apellidos}}</p>
{% empty %}
	<p>No hay clientes</p>
{% endfor %}-->
{% endblock %}

templates/clientes/nuevoFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/estilo_especial.css' %}">
{% endblock %}

{% block content %}

<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-6">
			<h1 class="text-center mb-4">Registro de nuevo cliente</h1>
			<form method="post">
				{% csrf_token %}
				{{form.as_p}}
				<button type="submit" class="btn btn-success">Registrar</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/clientes/paginaEspecial.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/estilo_especial.css' %}">
{% endblock %}

{% block content %}

<a class="btn btn-primary mb-3 ml-4" href="{% url 'clientes:nuevoRegistro' %}">Nuevo registro</a>

{% include 'base/info.html' %}
<!--{% for cliente in clientes %}
	<p>{{cliente.nombre}} {{cliente.apellidos}}</p>
{% empty %}
	<p>No hay clientes</p>
{% endfor %}-->

{% endblock %}